### ISSUE TITLE
Support Android XML files

### ISSUE THREAD

**Issue by kyze8439690** [ObservedObserver/chatgpt-i18n#11]
https://developer.android.com/training/basics/supporting-devices/languages

**Comment by ObservedObserver** [comment]
> I can implement it. Can you assign this to me? @ObservedObserver

Sure, thanks a lot.

**Comment by laterdayi** [comment]
ref https://github.com/ObservedObserver/chatgpt-i18n/issues/9

**Comment by zivnadel** [comment]
@ObservedObserver I haven't finished this yet. Is this irrelevant?
