### ISSUE TITLE
SyntaxError: Unexpected token `A', "An error o"... is not valid json but it is a valid json

### ISSUE THREAD

**Issue by Jackiexiao** [ObservedObserver/chatgpt-i18n#12]
![image](https://user-images.githubusercontent.com/18050469/233548924-01e0ddb5-8317-423b-b28d-6ca9a4ad9c01.png)

json below

```json
{
	"commands": {
		"checkValidity": {
			"inBranch": {
				"error403": "Error 403: {{- repo.owner}}/{{- repo.repo}} was moved permanently (from {{- branchInfo}}).",
				"error404": "Error 404: The branch {{- branchInfo}} was not found in {{- repo.owner}}/{{- repo.repo}}."
			},
			"inRepo": {
				"error301": "Error 301: {{- repo.owner}}/{{- repo.repo}}  was moved permanently.",
				"error403": "Error 403: this action is forbidden for {{- repo.owner}}/{{- repo.repo}}.",
				"error404": "Error 404: {{- repo.owner}}/{{- repo.repo}}: is not found."
			},
			"repoExistsTestBranch": "Repository {{- repo.owner}}/{{- repo.repo}} exists. Now testing the {{- main}} branch.",
			"dsfsadfsdafsd": "Repository {{- repo.owner}}/{{- repo.repo}} exists. Now testing the {{- main}} branch."
		}
    }
}
```

**Comment by ObservedObserver** [comment]
![image](https://user-images.githubusercontent.com/22167673/233606287-d2b0d940-614f-438f-9dd4-0d863c3cb31f.png)

It works fine at the online version.

If you are using this repo at local devices, remember to add your openai key at .env file

**Comment by Jackiexiao** [comment]
This is strange, I used the same code as you and deployed it on Vercel, and also correctly set the API key by vercel environment

https://chatgpt-i18n-kappa.vercel.app/translate

fork: https://github.com/jackiexiao/chatgpt-i18n

**Comment by Jackiexiao** [comment]
if I delete last two lines, everything works fine in my website

![image](https://user-images.githubusercontent.com/18050469/233609230-2b7eb48c-c031-4137-ad33-d8f7279d4625.png)

**Comment by ObservedObserver** [comment]
Your deployment caught a error with:

```
An error occurred with your deployment.

FUNCTION_INVOCATION_TIMEOUT
```
It seems you are using a free plan of Vercel, which only provides 10s usage limit for each function service. It is easy to get a timeout for chatgpt is pretty slow at this task.

**Comment by ObservedObserver** [comment]
You can upgrade your Vercel subscription (Pro = 60s) or use AWS lambda(which provides 15min per function).

**Comment by Jackiexiao** [comment]
oh!! thx for your reply!! I get

**Comment by Jackiexiao** [comment]
I am a new beginner here, could you tell me how to get this detail error message? I look in vercel log and could not find this error message `FUNCTION_INVOCATION_TIMEOUT`

![image](https://user-images.githubusercontent.com/18050469/233612887-444e8a47-7314-44d1-83fc-42e9fae40dbc.png)

**Comment by Jackiexiao** [comment]
thx!!
