### ISSUE TITLE
Error on local dev mode 

### ISSUE THREAD

**Issue by chandanrjit** [ObservedObserver/chatgpt-i18n#4]
Hey , I am getting error while running the code on local . Anything I am missing here ?
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/10242233/227771199-3f2384ea-8037-4875-945b-05c1d205d3c4.png">

**Comment by ObservedObserver** [comment]
I think it was caused by your backend not starting. Try `vercel dev` for local dev.

**Comment by chandanrjit** [comment]
that error is gone.  Thanks for that. now a new one 
<img width="925" alt="image" src="https://user-images.githubusercontent.com/10242233/231417540-ce4120e5-14e1-403d-aaff-023b91cf59b8.png">

**Comment by chandanrjit** [comment]
Key was expired . Now it's working . thanks

**Comment by chandanrjit** [comment]
Thanks @ObservedObserver  for the help
