### ISSUE TITLE
How to give a context to ChatGPT?

### ISSUE THREAD

**Issue by dario30186** [ObservedObserver/chatgpt-i18n#5]
Hi,
Thank you very much for sharing this very useful tool with the community.
I use ChatGPT for some translations but first I provide it with context for a more accurate translation.
For example I tell him:
translate this sentence concerning an Italian cooking blog, use informal language.
Would it be possible to add this functionality?

**Comment by ObservedObserver** [comment]
Great idea. It's not difficult to add customized prompts. But I think it requires the user to spend some time to test what prompt might work better.

**Comment by dariomines** [comment]
> ![image](https://user-images.githubusercontent.com/22167673/229574693-0c590570-ca74-4a99-8206-d26d41c0c584.png)
> 
> Updated in the latest commit. I tested some examples, and seems it effect differently in different languages.

Great!! Thank you very much!

**Comment by dario30186** [comment]
@ObservedObserver thank you so much!
