### ISSUE TITLE
support YML file

### ISSUE THREAD

**Issue by laterdayi** [ObservedObserver/chatgpt-i18n#9]
support YML file

**Comment by laterdayi** [comment]
Look forward to help @zivnadel  @ObservedObserver

**Comment by laterdayi** [comment]
@zivnadel @ObservedObserver   Are you making progress?

**Comment by zivnadel** [comment]
@laterdayi I'm waiting for the owner to respond

**Comment by laterdayi** [comment]
@zivnadel  Expected realization
